name: Dotnet Publish

on:
  release:
    types: [published]

env:
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    name: 'Build Deployment Package'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ env.RELEASE_TAG }}
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_TAG }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: dotnet publish
        run: dotnet publish ./Childrens-Social-Care-CPD-Indexer/Childrens-Social-Care-CPD-Indexer.csproj -c Release -o ./publish
        working-directory: ./src

      - name: Zip output
        run: zip -r ../${{ env.RELEASE_TAG }}.zip ./
        working-directory: ./src/publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resource-indexing-deployment
          path: ./src/${{ env.RELEASE_TAG }}.zip