name: Function App Deploy

on:
  release:
    types: [published]
    inputs:
      workspace:
        description: 'Environment to deploy to'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Test
          - Pre-Prod
          - Prod
          - Load-Test
          
jobs:
  build:
    name: 'Function App Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Sign in to Azure 
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.FAD_CLIENT_ID }}","clientSecret":"${{ secrets.FAD_CLIENT_SECRET }}","subscriptionId":"${{ secrets.FAD_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.FAD_TENANT_ID }}"}'

      - name: Deploy Function App
        run:  az functionapp deployment source config --branch main --manual-integration --name ${{ vars.FAD_FUNCTION_APP_NAME }} --repo-url ${{ github.event.repository.name }} --resource-group ${{ vars.FAD_RESOURCE_GROUP }}
